### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode...

### ISSUE THREAD

**Issue by i-zhivetiev** [gnss-lab/tec-suite#5]
```
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin/tecs", line 11, in <module>
    load_entry_point('tec-suite==0.7.4', 'console_scripts', 'tecs')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tecs/__main__.py", line 695, in run
    error_count = main()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tecs/__main__.py", line 219, in main
    obs = obs_file(o_file)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tecs/rinex/__init__.py", line 49, in obs_file
    f_obj = expand_obs(filename)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tecs/rinex/futils.py", line 227, in expand_obs
    for line in crx2rnx_pipe.stdout:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 967: invalid start byte
```

File: [pin11470.94d.zip](https://github.com/gnss-lab/tec-suite/files/1009140/pin11470.94d.zip)

**Comment by i-zhivetiev** [comment]
[casc.zip](https://github.com/gnss-lab/tec-suite/files/1053835/casc.zip)
